version: 2

project_name: argo-diff

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: argo-diff
    main: ./cmd/server
    binary: argo-diff
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip

kos:
  - id: argo-diff
    repository: ghcr.io/tamcore/argo-diff
    tags:
      - "{{ .Version }}"
      - latest
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64
    sbom: none
    labels:
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.source: "https://github.com/tamcore/argo-diff"

nfpms:
  - id: argo-diff
    package_name: argo-diff
    vendor: tamcore
    homepage: https://github.com/tamcore/argo-diff
    maintainer: tamcore <github@tamcore.io>
    description: ArgoCD diff preview service for GitHub PRs
    license: Apache-2.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: ./docs/examples/systemd.service
        dst: /lib/systemd/system/argo-diff.service
        type: config
    scripts:
      postinstall: scripts/postinstall.sh
      preremove: scripts/preremove.sh

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
  groups:
    - title: "New Features"
      regexp: '^feat(\(.+\))?:'
      order: 0
    - title: "Bug Fixes"
      regexp: '^fix(\(.+\))?:'
      order: 1
    - title: "Performance Improvements"
      regexp: '^perf(\(.+\))?:'
      order: 2
    - title: "Other Changes"
      order: 999

release:
  github:
    owner: tamcore
    name: argo-diff
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"
